println("initialize():")
@time initialize("data/SARS-CoV-2/protein/covid_proteins.fasta")
println("get_ID:")
@time get_ID("data/SARS-CoV-2/protein/covid_proteins.fasta")
println("get_SEQ():")
@time get_SEQ("data/SARS-CoV-2/protein/covid_proteins.fasta")
println("get_ID_SEQ():")
@time get_ID_DESC("data/SARS-CoV-2/protein/covid_proteins.fasta")
#measure subsequent invocations because compilation time
println("get_ID_SEQ():")
@time get_ID_DESC("data/SARS-CoV-2/protein/covid_proteins.fasta")
@time get_ID_DESC("data/SARS-CoV-2/protein/covid_proteins.fasta")
@time get_ID_DESC("data/SARS-CoV-2/protein/covid_proteins.fasta")
@time get_ID_DESC("data/SARS-CoV-2/protein/covid_proteins.fasta")
@time get_ID_DESC("data/SARS-CoV-2/protein/covid_proteins.fasta")
@time get_ID_DESC("data/SARS-CoV-2/protein/covid_proteins.fasta")
@time get_ID_DESC("data/SARS-CoV-2/protein/covid_proteins.fasta")
